name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Explicit MSTest test
      run: |
        cp tests/UnitTestEx.Api/bin/Debug/netcoreapp3.1/UnitTestEx.Api.deps.json tests/UnitTestEx.MSTest.Test/bin/Debug/netcoreapp3.1
        cd tests/UnitTestEx.MSTest.Test/bin/Debug/netcoreapp3.1
        dotnet test UnitTestEx.MSTest.Test.dll --no-build --verbosity normal
    - name: Explicit NUnit test
      run: |
        cp tests/UnitTestEx.Api/bin/Debug/netcoreapp3.1/UnitTestEx.Api.deps.json tests/UnitTestEx.NUnit.Test/bin/Debug/netcoreapp3.1
        cd tests/UnitTestEx.NUnit.Test/bin/Debug/netcoreapp3.1
        dotnet test UnitTestEx.NUnit.Test.dll --no-build --verbosity normal
    - name: Explicit Xunit test
      run: |
        cp tests/UnitTestEx.Api/bin/Debug/netcoreapp3.1/UnitTestEx.Api.deps.json tests/UnitTestEx.Xunit.Test/bin/Debug/netcoreapp3.1
        cd tests/UnitTestEx.Xunit.Test/bin/Debug/netcoreapp3.1
        dotnet test UnitTestEx.Xunit.Test.dll --no-build --verbosity normal --tests MockHttpClientTest
        dotnet test UnitTestEx.Xunit.Test.dll --no-build --verbosity normal --tests PersonFunctionTest
        dotnet test UnitTestEx.Xunit.Test.dll --no-build --verbosity normal --tests ProductFunctionTest
        dotnet test UnitTestEx.Xunit.Test.dll --no-build --verbosity normal --tests ServiceBusFunctionTest
        dotnet test UnitTestEx.Xunit.Test.dll --no-build --verbosity normal --tests PersonControllerTest
        dotnet test UnitTestEx.Xunit.Test.dll --no-build --verbosity normal --tests ProductControllerTest